---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Drive
  labels:
    app: Drive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Drive
  template:
    metadata:
      labels:
        app: Drive
    spec:
      containers:
        - name: Drive
          image: username/Drive:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Indexer
  labels:
    app: Indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Indexer
  template:
    metadata:
      labels:
        app: Indexer
    spec:
      containers:
        - name: Indexer
          image: username/Indexer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: VideoProcessing
  labels:
    app: VideoProcessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VideoProcessing
  template:
    metadata:
      labels:
        app: VideoProcessing
    spec:
      containers:
        - name: VideoProcessing
          image: username/VideoProcessing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Notification
  template:
    metadata:
      labels:
        app: Notification
    spec:
      containers:
        - name: Notification
          image: username/Notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Dashboard
  labels:
    app: Dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dashboard
  template:
    metadata:
      labels:
        app: Dashboard
    spec:
      containers:
        - name: Dashboard
          image: username/Dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Drive
  labels:
    app: Drive
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Drive


---


apiVersion: v1
kind: Service
metadata:
  name: Indexer
  labels:
    app: Indexer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Indexer


---


apiVersion: v1
kind: Service
metadata:
  name: VideoProcessing
  labels:
    app: VideoProcessing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: VideoProcessing


---


apiVersion: v1
kind: Service
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Notification


---


apiVersion: v1
kind: Service
metadata:
  name: Dashboard
  labels:
    app: Dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Dashboard

