apiVersion: apps/v1
kind: Deployment
metadata:
  name: VideoProcessing
  labels:
    app: VideoProcessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VideoProcessing
  template:
    metadata:
      labels:
        app: VideoProcessing
    spec:
      containers:
        - name: VideoProcessing
          image: username/VideoProcessing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5